export { default as Landing } from './Landing'
export { default as Home } from './Home'
export { default as Recipes } from './Recipes'
export { default as Settings } from './Settings'
export { default as Utensils } from './Utensils'
export { default as Ingredients } from '../features/ingredients/ingredientsPage'
export { default as Auth } from '../features/auth/authPage'